language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_script:
  - psql -c 'create user transitandtrails' -U postgres
  - psql -c 'ALTER USER transitandtrails CREATEDB' -U postgres
  - psql -c 'create database transitandtrails_test owner transitandtrails' -U postgres
